.TH AALIB 1
.SH NAME
aafire, aainfo, aasavefont, aatest \- aalib example programs
.SH SYNOPSIS
.B aafire
.I "[options]"
.P
.B aainfo
.I "[options]"
.P
.B aasavefont
.I "[options] file_name variable_name long_name short_name"
.P
.B aatest
.I "[options]"
.SH "DESCRIPTION"
This manual page documents briefly the
.BR aafire ,
.BR aainfo ,
.BR aasavefont ,
and 
.BR aatest
programs.
.PP
All of these programs exist to demonstrate the capabilities of the aalib
library, an ascii art library.
.PP
.B aafire
displays burning ascii art flames.
.PP
.B aainfo
displays information about what drivers aalib will use for the display,
keyboard, and mouse, and what parameters, such as screen size those drivers
will use.
.PP
.B aasavefont
saves a font to a file.
.PP
.B aatest
tests the capabilities of aalib.
.SH AUTHOR
This manual page was written by Joey Hess,
for the Debian GNU/Linux system.
